{{ config(materialized='table') }}

WITH Source_data AS ( SELECT * FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA),

FINAL AS (
SELECT * FROM (SELECT MONTH(DATE::DATE) || '/' || YEAR(DATE::DATE) AS MONTH_YR, LOCATION,SUM(TOTAL_ACTIVE_CASES) AS ACTIVE_CASES FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA
GROUP BY 1,2
ORDER BY 1,2)
WHERE ACTIVE_CASES >= 0
)

SELECT * FROM FINAL
