{{ config(materialized='table') }}

WITH Source_data AS ( SELECT * FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA),

FINAL AS (
SELECT LOCATION,AVG(COALESCE(GROWTH_FACTOR_OF_NEW_DEATHS,0)) AS AVG_NEW_DEATH_GROWTH_FACTOR,AVG(COALESCE(GROWTH_FACTOR_OF_NEW_CASES,0)) AS AVG_NEW_CASE_GROWTH_FACTOR 
FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA
GROUP by 1
order by 1
)

SELECT * FROM FINAL
