{{ config(materialized='table') }}

WITH Source_data AS ( SELECT * FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA),

FINAL AS (
SELECT YEAR(DATE::DATE) AS YEAR,MONTH(DATE::DATE) AS MONTH,LOCATION,SUM(NEW_CASES_PER_MILLION) AS NEW_CASES_PER_MILLION_PER_MONTH,SUM(NEW_DEATHS_PER_MILLION) AS NEW_DEATHS_PER_MILLION_PER_MONTH
FROM INTERVIEW_DB.PLAYGROUND_KUNAL_KUYABA.COVID_RAW_DATA
GROUP BY 1,2,3
order by 3,1,2
)

SELECT * FROM FINAL
